/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef volatile unsigned int vuint32_t;
#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

// register address
//RCC reg
#define RCC_BASE 0x40021000
#define RCC_CFGR *(volatile uint32_t *)(RCC_BASE + 0x04)
#define RCC_CR *(volatile uint32_t *)(RCC_BASE + 0x00)
#define RCC_APB2ENR *(vuint32_t *)(RCC_BASE + 0x18)
#define RCC_IOPAEN (1<<2)
#define RCC_AFIOEN (1<<0)
//GPIO reg
#define GPIOA_BASE  0x40010800
#define GPIOA_CRL	*(vuint32_t *)(GPIOA_BASE + 0x00)
#define GPIOA_CRH   *(vuint32_t *)(GPIOA_BASE + 0x04)
#define GPIOA_ODR   *(vuint32_t *)(GPIOA_BASE + 0x0C)
//AFIO reg
#define AFIO_BASE	0x40010000
#define AFIO_EXTICR1	*(vuint32_t *)(AFIO_BASE + 0x08)

//EXTI reg
#define EXTI_BASE	0x40010400
#define EXTI_IMR	*(vuint32_t *)(EXTI_BASE + 0x00)
#define EXTI_RTSR	*(vuint32_t *)(EXTI_BASE + 0x08)
#define EXTI_PR	*(vuint32_t *)(EXTI_BASE + 0x14)
//NVIC Interrupt set-enable reg in the cortex m
#define NVIC_ISER0 *(vuint32_t *)(0xE000E100)

void clockInit(){
	RCC_APB2ENR |= RCC_IOPAEN;
	RCC_APB2ENR |= RCC_AFIOEN;
}
void GPIO_Pin13_Output_init(){
	GPIOA_CRH &= 0xFF0FFFFF;
	GPIOA_CRH |= 0x00200000;
}
void GPIO_Pin0_Input_init(){
	GPIOA_CRL |= (1<<2);
}
int main(void) {
	clockInit();
	GPIO_Pin0_Input_init();
	GPIO_Pin13_Output_init();
	AFIO_EXTICR1 &= 0xFFFFFFF0;

	EXTI_IMR |= (1<<0);
	EXTI_RTSR |= (1<<0);
	//En NCIC IRQ 6 (EXTI0)
	NVIC_ISER0 |= (1<<6);

	while (1) {

	}
}

void EXTI0_IRQHandler(void){
	GPIOA_ODR ^= (1<<13);

	EXTI_PR |= (1<<0);
}

